# Codecov Configuration
# https://docs.codecov.io/docs/codecov-yaml

coverage:
  precision: 2
  round: down
  range: "70...100"
  status:
    project:
      default:
        target: 80%
        threshold: 5%
    patch:
      default:
        target: 80%
        threshold: 5%

ignore:
  - "tests/**/*"
  - "docs/**/*"
  - "examples/**/*"
  - "setup.py"
  - "**/__pycache__/**/*"

comment:
  layout: "header, diff, files"
  behavior: default
  require_changes: false
